### ISSUE TITLE
Page tpl no grid view for 1st/2nd side bar

### ISSUE THREAD

**Issue by iijiang** [govau/message-lab-theme#6]
I am not sure why you leave 1st/2nd sidebar not into a row grid, which I felt it should be. I got fixing here let me know if you need.

**Comment by imperator99** [comment]
Hi Yi,
The site doesn't use sidebars so I haven't styled them at all. Remember that this theme is used for a specific site and I haven't paid much attention to how it might be implemented elsewhere. 
If you think your change might be useful please submit a PR and I'll take a look.
Cheers,
Jesse.
